---
- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      ignore_errors: yes

    - name: Download Kubernetes apt key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /tmp/apt-key.gpg

    - name: Add Kubernetes apt key from the downloaded file
      apt_key:
        file: /tmp/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-focal main"
        state: present
        filename: "kubernetes"
      ignore_errors: yes

    - name: Install kubeadm, kubelet, and kubectl with --allow-unauthenticated
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes
        force: yes
        allow_unauthenticated: yes
      ignore_errors: yes

    - name: Hold kubeadm, kubelet, and kubectl at current version
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: held
      ignore_errors: yes

    - name: Copy join command from Ansible host to the worker nodes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes to the cluster
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - name: Check the status of the join command
      debug:
        var: joined_or_not.stdout_lines
