- hosts: masters
  become: yes
  tasks:
    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name:
          - kubeadm=1.28.13-1.1
          - kubelet=1.28.13-1.1
          - kubectl=1.28.13-1.1
        state: present
        update_cache: yes
        allow_change_held_packages: yes

    - name: Hold kubeadm, kubelet, and kubectl at the current version
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        allow_change_held_packages: yes

    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become_user: kube
      file:
        path: /home/kube/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube
        mode: '0644'

    - name: Install Pod network
      become_user: kube
      shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Debug join command
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file
      local_action:
        module: copy
        content: "{{ kubernetes_join_command.stdout }}"
        dest: "/tmp/kubernetes_join_command"
        mode: '0777'
      delegate_to: localhost
      become: no
